**CALIBRACIÓN**


In [15]:
cd /home/juanjo/workspace/umucv/code

/home/juanjo/workspace/umucv/code


In [37]:
! python stream.py --dev=4

640x480 30.0fps
Gtk-Message: 11:38:15.033: Failed to load module "atk-bridge"
Gtk-Message: 11:38:15.035: Failed to load module "canberra-gtk-module"


In [38]:
! python calibrate/calibrate.py ../Practicas/cam/*

processing ../Practicas/cam/20210321-113839.png...
ok
RMS: 0.07056619347305547
camera matrix:
 [[417.07162981   0.         310.98136052]
 [  0.         416.70667229 247.83116092]
 [  0.           0.           1.        ]]
distortion coefficients:  [ 1.79981576e-01 -5.64329180e-01 -3.06243790e-03 -6.52323286e-04
  1.16065268e+00]


In [2]:
import numpy as np
import cv2   as cv

K= np.array([[ 417.07162981,    0.,          310.98136052],
             [   0.,          416.70667229,  247.83116092],
             [   0.,            0.,            1.        ]])
d = np.array([ 0.179981576,  -0.56432918,  -0.00030624, -0.000065232,  1.160652])

img = cv.imread("/home/juanjo/workspace/umucv/Practicas/cam/20210321-113839.png")
h, w = img.shape[:2]

# undistort
newcamera, roi = cv.getOptimalNewCameraMatrix(K, d, (w,h), 0) 
newimg = cv.undistort(img, K, d, None, newcamera)

print(newcamera)
print(roi)

cv.imshow("jambo", newimg)


[[596.75427246   0.         326.31211142]
 [  0.         605.97363281 240.01852558]
 [  0.           0.           1.        ]]
(0, 0, 640, 480)
